### ISSUE TITLE
Invalid Version: undefined

### ISSUE THREAD

**Issue by ApeAaron** [ourcade/phaser3-typescript-parcel-template#2]
Hello! 
I followed the instructions, downloaded the dependencies and ran the npm server as detailed, however, once I ran it, I got the following error.

phaser3-typescript-parcel-template/src/main.ts: Invalid Version: undefined

I have not modified or altered the code in anyway. 

I apologize in advance if this is not an issue with the project, but rather my end, as I have done very little web-dev. 

Thanks in advance! 

Here is the full error from the terminal 

```
home/user/Desktop/phaser3-typescript-parcel-template/src/main.ts: Invalid Version: undefined
    at new SemVer (/home/user/.nvm/versions/node/v15.11.0/lib/node_modules/parcel-bundler/node_modules/@babel/preset-env/node_modules/semver/semver.js:314:11)
    at compare (/home/user/.nvm/versions/node/v15.11.0/lib/node_modules/parcel-bundler/node_modules/@babel/preset-env/node_modules/semver/semver.js:647:10)
    at lt (/home/user/.nvm/versions/node/v15.11.0/lib/node_modules/parcel-bundler/node_modules/@babel/preset-env/node_modules/semver/semver.js:688:10)
    at /home/user/.nvm/versions/node/v15.11.0/lib/node_modules/parcel-bundler/node_modules/@babel/preset-env/lib/index.js:276:22
    at Object.default (/home/user/.nvm/versions/node/v15.11.0/lib/node_modules/parcel-bundler/node_modules/@babel/helper-plugin-utils/lib/index.js:22:12)
    at getEnvPlugins (/home/user/.nvm/versions/node/v15.11.0/lib/node_modules/parcel-bundler/src/transforms/babel/env.js:62:34)
    at getEnvConfig (/home/user/.nvm/versions/node/v15.11.0/lib/node_modules/parcel-bundler/src/transforms/babel/env.js:12:25)
    at async getBabelConfig (/home/user/.nvm/versions/node/v15.11.0/lib/node_modules/parcel-bundler/src/transforms/babel/config.js:32:19)
    at async babelTransform (/home/user/.nvm/versions/node/v15.11.0/lib/node_modules/parcel-bundler/src/transforms/babel/transform.js:6:16)
    at async JSAsset.pretransform (/home/user/.nvm/versions/node/v15.11.0/lib/node_modules/parcel-bundler/src/assets/JSAsset.js:83:5)

```

**Comment by ApeAaron** [comment]
Resolved the issue! It seems to be related to a bug in the newest version of the parcel-bundler, I resolved it by following the advice [here](https://stackoverflow.com/questions/66459081/parcel-semver-bug) and rolling back the version.
